<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Category;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCategoriesBySectionAndParent($section, Category $parent = null)
    {
        $query = $this->createQueryBuilder('c')
            ->where('c.section = :section')
            ->setParameter('section', $section);

        if(isset($parent)){
            $query->andWhere('c.parent = :parent')
                ->setParameter('parent', $parent->getId());
        } else {
            $query->andWhere($query->expr()->isNull('c.parent'));
        }

        return $query->getQuery()->getResult();
    }
}
