<?php

namespace AppBundle\Repository;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileUploadedRepository extends \Doctrine\ORM\EntityRepository
{
}
